import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient, type UseQueryResult } from "@tanstack/react-query";
import { Building2, Check, KeyRound, ScrollText, Settings, Shield, UserPlus } from "lucide-react";
import { EmptyState, ErrorState, LoadingState } from "../components/AsyncStates";
import { useAuth } from "../contexts/useAuth";
import { createServiceAccount, getAudit, getMembers, getServiceAccounts, getWorkspace, inviteMember, type ServiceAccount, type WorkspaceMember } from "../services/authApi";
import { getApiErrorMessage } from "../services/apiClient";
import "../workspace-identity.css";

const tabs = ["Overview", "Members", "Roles", "Service Accounts", "Audit", "Settings"] as const;
type Tab = (typeof tabs)[number];

export function WorkspacePage({ selectionOnly = false }: { selectionOnly?: boolean }) {
  const auth = useAuth();
  const queryClient = useQueryClient();
  const [tab, setTab] = useState<Tab>("Overview");
  const active = auth.session?.workspaces.find(item => item.id === auth.session?.activeWorkspaceId);
  if (selectionOnly) return <section className="workspace-select-page"><header><span className="page-heading-icon"><Building2 /></span><div><span className="panel-eyebrow">Workspace access</span><h1>Select a workspace</h1><p>Your active workspace scopes every capability and query.</p></div></header><div className="workspace-choice-grid">{auth.session?.workspaces.map(item => <button key={item.id} className={`workspace-choice-card${item.id === active?.id ? " selected" : ""}`} onClick={() => auth.switchWorkspace(item.id)}><span><Building2 /></span><div><strong>{item.name}</strong><small>{item.role}</small></div>{item.id === active?.id && <Check />}</button>)}</div></section>;
  if (!active) return <EmptyState title="No active workspace" description="Select a workspace to continue." />;
  const isAdmin = active.role === "Administrator";
  return <section className="workspace-admin-page page-stack"><header className="page-heading"><span className="page-heading-icon"><Building2 /></span><div><span className="panel-eyebrow">Organisation and access</span><h1>{active.name}</h1><p>Manage members, service identities, roles, security activity, and workspace settings.</p></div><select aria-label="Active workspace" value={active.id} onChange={event => auth.switchWorkspace(event.target.value)}>{auth.session?.workspaces.map(item => <option value={item.id} key={item.id}>{item.name} · {item.role}</option>)}</select></header><nav className="workspace-tabs" aria-label="Workspace administration">{tabs.map(item => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</nav>{!isAdmin && tab !== "Overview" ? <div className="panel restricted-state"><Shield /><h2>Administrator permission required</h2><p>Your {active.role} role can use workspace capabilities but cannot manage access.</p></div> : <WorkspaceTab tab={tab} workspaceId={active.id} onInvalidate={key => queryClient.invalidateQueries({ queryKey: [key, active.id] })} />}</section>;
}

function WorkspaceTab({ tab, workspaceId, onInvalidate }: { tab: Tab; workspaceId: string; onInvalidate: (key: string) => void }) {
  const workspace = useQuery({ queryKey: ["workspace", workspaceId], queryFn: () => getWorkspace(workspaceId), enabled: tab === "Overview" || tab === "Settings" });
  const members = useQuery({ queryKey: ["workspace-members", workspaceId], queryFn: () => getMembers(workspaceId), enabled: tab === "Members" || tab === "Roles" });
  const accounts = useQuery({ queryKey: ["service-accounts", workspaceId], queryFn: () => getServiceAccounts(workspaceId), enabled: tab === "Service Accounts" });
  const audit = useQuery({ queryKey: ["workspace-audit", workspaceId], queryFn: () => getAudit(workspaceId), enabled: tab === "Audit" });
  if (tab === "Overview") return <div className="workspace-overview-grid"><article className="panel"><span className="panel-eyebrow">Workspace</span>{workspace.isLoading ? <LoadingState compact /> : workspace.isError ? <ErrorState message={getApiErrorMessage(workspace.error)} onRetry={() => workspace.refetch()} /> : <><h2>{workspace.data?.name}</h2><dl><div><dt>Status</dt><dd>{workspace.data?.status}</dd></div><div><dt>Slug</dt><dd>{workspace.data?.slug}</dd></div><div><dt>Revision</dt><dd>{workspace.data?.revision}</dd></div></dl><p>{workspace.data?.description}</p></>}</article><article className="panel"><span className="panel-eyebrow">Isolation</span><h2>Server-enforced ownership</h2><p>Every capability root is filtered by the trusted workspace context. Guessed cross-workspace identifiers resolve as not found.</p></article></div>;
  if (tab === "Members") return <MembersPanel workspaceId={workspaceId} query={members} onChanged={() => onInvalidate("workspace-members")} />;
  if (tab === "Roles") return <section className="panel role-grid">{[{ name: "Administrator", copy: "Full workspace, membership, service-account, governance, publication, and execution access." }, { name: "Engineer", copy: "Build assets, draft governance, execute simulations and replays, and inspect sensitive traces." }, { name: "Reviewer", copy: "Review and publish controlled assets, evaluations, replays, and policies." }, { name: "Operator", copy: "Run approved workloads and inspect operational traces, decisions, and provider health." }, { name: "Viewer", copy: "Read non-sensitive workspace resources." }].map(role => <article key={role.name}><Shield /><div><h3>{role.name}</h3><p>{role.copy}</p></div></article>)}</section>;
  if (tab === "Service Accounts") return <ServiceAccountsPanel workspaceId={workspaceId} query={accounts} onChanged={() => onInvalidate("service-accounts")} />;
  if (tab === "Audit") return <section className="panel audit-panel"><div className="panel-header"><div><span className="panel-eyebrow">Append-only activity</span><h2>Audit events</h2></div><ScrollText /></div>{audit.isLoading ? <LoadingState compact /> : audit.isError ? <ErrorState message={getApiErrorMessage(audit.error)} onRetry={() => audit.refetch()} /> : !audit.data?.length ? <EmptyState title="No audit events yet" description="Governed activity will appear here." /> : <div className="audit-list">{audit.data.map(item => <article key={item.id}><span>{item.actorType}</span><div><strong>{item.action}</strong><p>{item.actorDisplay} · {item.resourceType}</p><small>Correlation {item.correlationId}</small></div><time>{new Date(item.occurredAt).toLocaleString("en-ZA")}</time></article>)}</div>}</section>;
  return <section className="panel settings-panel"><Settings /><div><h2>Workspace settings</h2><p>Environment promotion and organisation-wide sharing are intentionally deferred beyond alpha.12.</p><dl><div><dt>Organisation</dt><dd>{workspace.data?.organisationId}</dd></div><div><dt>Workspace ID</dt><dd>{workspace.data?.id}</dd></div></dl></div></section>;
}

function MembersPanel({ workspaceId, query, onChanged }: { workspaceId: string; query: UseQueryResult<WorkspaceMember[], Error>; onChanged: () => void }) {
  const [open, setOpen] = useState(false); const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [role, setRole] = useState("Viewer");
  const mutation = useMutation({ mutationFn: () => inviteMember(workspaceId, { email, displayName: name, role }), onSuccess: () => { setOpen(false); setEmail(""); setName(""); onChanged(); } });
  return <section className="panel"><div className="panel-header"><div><span className="panel-eyebrow">People</span><h2>Members</h2></div><button className="primary-button" onClick={() => setOpen(value => !value)}><UserPlus />Invite member</button></div>{open && <form className="workspace-inline-form" onSubmit={(event: FormEvent) => { event.preventDefault(); mutation.mutate(); }}><input aria-label="Email" type="email" placeholder="name@company.com" value={email} onChange={event => setEmail(event.target.value)} required /><input aria-label="Display name" placeholder="Display name" value={name} onChange={event => setName(event.target.value)} required /><select aria-label="Role" value={role} onChange={event => setRole(event.target.value)}>{["Administrator", "Engineer", "Reviewer", "Operator", "Viewer"].map(item => <option key={item}>{item}</option>)}</select><button className="primary-button" disabled={mutation.isPending}>{mutation.isPending ? "Inviting…" : "Create invitation"}</button>{mutation.isError && <p role="alert">{getApiErrorMessage(mutation.error)}</p>}</form>}{query.isLoading ? <LoadingState compact /> : query.isError ? <ErrorState message={getApiErrorMessage(query.error)} onRetry={() => query.refetch()} /> : <div className="member-list">{query.data?.map(item => <article key={item.id}><span className="member-avatar">{item.displayName.split(" ").map(value => value[0]).slice(0, 2).join("")}</span><div><strong>{item.displayName}</strong><small>{item.email}</small></div><span className="role-pill">{item.role}</span><span>{item.status}</span></article>)}</div>}</section>;
}

function ServiceAccountsPanel({ workspaceId, query, onChanged }: { workspaceId: string; query: UseQueryResult<ServiceAccount[], Error>; onChanged: () => void }) {
  const [name, setName] = useState(""); const [credential, setCredential] = useState<string>();
  const mutation = useMutation({ mutationFn: () => createServiceAccount(workspaceId, { name, scopes: ["WorkspaceMember", "CanRunSimulation", "CanViewOperationalTrace"] }), onSuccess: (value: { credential: string }) => { setCredential(value.credential); setName(""); onChanged(); } });
  return <section className="panel"><div className="panel-header"><div><span className="panel-eyebrow">Machine identities</span><h2>Service accounts</h2></div></div><form className="workspace-inline-form" onSubmit={(event: FormEvent) => { event.preventDefault(); mutation.mutate(); }}><input aria-label="Service account name" value={name} onChange={event => setName(event.target.value)} placeholder="Automation runner" required /><button className="primary-button" disabled={mutation.isPending}><KeyRound />{mutation.isPending ? "Creating…" : "Create credential"}</button></form>{credential && <div className="credential-reveal" role="status"><strong>Copy this credential now</strong><code>{credential}</code><small>It is never stored or shown again.</small></div>}{query.isLoading ? <LoadingState compact /> : query.isError ? <ErrorState message={getApiErrorMessage(query.error)} onRetry={() => query.refetch()} /> : !query.data?.length ? <EmptyState title="No service accounts" description="Create a scoped identity for automation." /> : <div className="member-list">{query.data.map(item => <article key={item.id}><KeyRound /><div><strong>{item.name}</strong><small>Last used {item.lastUsedAt ? new Date(item.lastUsedAt).toLocaleString("en-ZA") : "Never"}</small></div><span className="role-pill">{item.status}</span><span>r{item.revision}</span></article>)}</div>}</section>;
}
